config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "events#index"
  get "pages/politika"

  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]
    post :show, on: :member
  end
  resources :users, only: %i[show edit update]
  get '/404', to: "errors#not_found"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    subscribers + [user]
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, only: %i[show edit update destroy]
  before_action :password_guard!, only: :show

  after_action :verify_authorized, only: %i[show edit create update destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    @events = policy_scope(Event)
  end

  def show
    authorize @event
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)
    authorize @event

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    authorize @event
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def password_guard!
    return true if @event.pincode.blank?
    return true if signed_in? && current_user == @event.user

    if params[:pincode].present? && @event.pincode_valid?(params[:pincode]) && signed_in?
      cookies.permanent["events_#{@event.id}_pincode_#{current_user.id}"] = params[:pincode]
    end

    pincode = cookies.permanent["events_#{@event.id}_pincode_#{current_user.id}"] if signed_in?
    pincode = params[:pincode] unless signed_in?

    return if @event.pincode_valid?(pincode)

    flash.now[:alert] = I18n.t('controllers.events.wrong_pincode') if params[:pincode].present?
    render 'password_form'
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4 pt-2">
  <div class="thumbnail">
    <%= content_tag :div, '', class: 'event-background', style: "background-image: url(#{event_photo(event)})"%>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description pl-2">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3><small><%= l(event.datetime, format: :short) %></small></h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p>
      <%= f.text_field :datetime, class: 'form-control datepicker-here col-4',
                        data: { timepicker: true} %>
    </p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit t('links.save'), class: 'btn btn-primary' %>
    <%= t('inscription.or') %> <%= link_to t('links.to_return'), :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1 class="border-bottom text-dark pb-2"><%= t('heading.editing_event') %></h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>
<div class="row pt-4">
  <div class="col-md-6 buffer-top">
    <h3><%= t('heading.delete_event') %></h3>
    <%= link_to t('links.delete_event'), event_path(@event),
                data: {confirm: t('questions.are_you_sure')},
                method: :delete, class: 'btn btn-danger' %>
  </div>
</div>

app/views/events/index.html.erb
<h1 class="border-bottom text-dark pb-2"><%= t('heading.event') %></h1>


<div class="buffer-both">
  <%= link_to  t('links.сreate_event'), new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1 class="border-bottom text-dark pb-2"><%= t('heading.new_event') %></h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1 class="border-bottom text-dark pb-2"><%= t('heading.access_only_by_pin_code') %></h1>
<div class="col-sm-6 col-md-4 pt-2">
  <%= form_for('', method: 'post') do |f| %>
    <div class="form-group">
      <%= f.label :pincode, t('inscription.pincode') %>
      <%= f.password_field :pincode, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit t('links.save'), class: 'btn btn-primary' %>
    </div>
  <% end %>
  <%= link_to t('links.to_home'), events_path %>
</div>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col">
      <%= content_tag 'div', '', class: 'event-background', style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description buffer-both">
            <h1><%= @event.title %></h1>
            <h3><%= l(@event.datetime, format: :short) %></h3>
            <h3><small><%= link_to @event.address,
                                   "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
            <p><%= @event.description %></p>
          </div>

          <% if policy(@event).edit? %>
            <div class="buffer-both">
              <%= link_to t('links.change'), edit_event_path(@event), class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 order-2">
      <div id="map" data-address="<%= @event.address %>"></div>
      <div class="event-photos-gallery pt-2 border-bottom">
        <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
      </div>
      <div class="event-photo-form pt-2">
        <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
      </div>
      <div class="event-comments buffer-top">
        <%= render partial: 'comments/form',
                   locals: {comment: @new_comment || @event.comments.build} %>

        <div class="buffer-both">
          <%= render partial: 'comments/comment',
                     collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-4 order order-md-2 pb-2">
      <div class="event-owner">
        <h4><%= t('heading.calling') %></h4>
        <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <% if @event.subscriptions.exists? %>
        <div class="event-subscriptions">
          <h4><%= t('heading.will_go') %></h4>
          <div>
            <p>
              <%= render partial: 'subscriptions/subscription',
                         collection: @event.subscriptions.except(@new_subscription) %>
            </p>
          </div>
        </div>
      <% end %>
      <% unless current_user_can_edit?(@event) %>
        <div class="event-subscription-form">
          <h4><%= t('heading.i_will_go') %></h4>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
                subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>